Sprint 3
ClevertecFrontendLab/Yura574 pull request #1
Opened 2023-02-16 20:47 UTC by Yura574

2023-02-16 20:50 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Yura574/1676580653/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Yura574/1676580653/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Yura574/1676580653/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Yura574/1676580653/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Yura574/1676580653/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Yura574/1676580653/main-loading.png)

2023-02-16 21:27 UTC, Gaurrus requested changes

2023-02-16 21:27 UTC, Gaurrus commented on .editorconfig
> +root = true
![image](https://user-images.githubusercontent.com/85307211/219488239-d37bebb2-ee6f-46af-b787-e96a07a3f77b.png)
категоря должна быть

2023-02-16 21:27 UTC, Gaurrus commented on src/components/initial-state.ts
> +    ],
это кому?) моки удаляем

2023-02-16 21:27 UTC, Gaurrus commented on src/components/main-section.tsx
> +            {/*/>*/}
ну если сделал, оставил бы)

2023-02-17 18:33 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- ErrorBookId -- bookId-error (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Yura574/1676658798/Get%20books%20test%20--%20ErrorBookId%20--%20bookId-error%20(failed).png)
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Yura574/1676658798/app-sucess.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Yura574/1676658798/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Yura574/1676658798/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Yura574/1676658798/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Yura574/1676658798/main-loading.png)

2023-02-17 18:40 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Yura574/1676659239/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Yura574/1676659239/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Yura574/1676659239/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Yura574/1676659239/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Yura574/1676659239/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Yura574/1676659239/main-loading.png)

2023-02-17 19:02 UTC, Gaurrus approved these changes

2023-02-17 19:02 UTC, merged